---

github:
- asvetlov
- webknjaz
- Dreamsorcerer
open_collective: aiohttp
tidelift: pypi/aiohttp  # A single Tidelift platform-name/package-name e.g., npm/babel
custom:
- https://opencollective.com/aio-libs

...
