codecov:
  branch: master
  notify:
    manual_trigger: true

comment:
  layout: "newheader, diff, flags, components, files"
  require_head: false
  require_base: false

coverage:
  range: "95..100"

component_management:
  individual_components:
    - component_id: project
      paths:
        - aiohttp/**
    - component_id: tests
      paths:
        - tests/**
