[run]
branch = true
plugins = [
  'Cython.Coverage',
]
omit = [
  'site-packages',
]

[report]
partial_also = [
  'if not TYPE_CHECKING',
]
exclude_also = [
  'if TYPE_CHECKING',
  'assert False',
  ': \.\.\.(\s*#.*)?$',
  '^ +\.\.\.$',
  'pytest.fail\('
]
