# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details

---
version: 2

submodules:
  include: all  # []
  exclude: []
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  commands:
  - >-
    python -m
    venv "${READTHEDOCS_VIRTUALENV_PATH}"
  - >-
    "${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -m
    pip install
    . -c requirements/runtime-deps.txt
    -r requirements/doc.in -c requirements/doc.txt
    readthedocs-sphinx-ext
  - >-
    pwd
  - >-
    ls -lah . docs/
  - >-
    cat docs/conf.py
  - >-
    "${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -m
    sphinx
    -j auto
    -T
    -E
    -b html
    -d "${READTHEDOCS_OUTPUT}"/_build/doctrees
    -D language=en
    docs/
    "${READTHEDOCS_OUTPUT}"/html

...
