# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details

---
version: 2

submodules:
  include: all  # []
  exclude: []
  recursive: true

build:
  image: latest
python:
  version: 3.8
  install:
  - method: pip
    path: .
  - requirements: requirements/doc.txt
...
