stages:
- stage: lint
  displayName: 'Lint'

  jobs:
  - job: 'flake8'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        pip install -r requirements/lint.txt
      displayName: 'Install deps'

    - script: |
        make flake8
      displayName: 'Run flake8'

  - job: 'isort'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        pip install -e .
      displayName: 'Install itself'
      env:
        AIOHTTP_NO_EXTENSIONS: 1

    - script: |
        pip install -r requirements/lint.txt
      displayName: 'Install deps'

    - script: |
        make isort-check
      displayName: 'Run isort checker'

  - job: 'mypy'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        pip install -r requirements/lint.txt
      displayName: 'Install deps'

    - script: |
        pip install -e .
      displayName: 'Install itself'
      env:
        AIOHTTP_NO_EXTENSIONS: 1

    - script: |
        make mypy
      displayName: 'Run black checker'

  - job: 'docs'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        apt install libenchant-dev
        pip install -r requirements/doc-spelling.txt
        pip install -r requirements/towncrier.txt
      displayName: 'Install deps'

    - script: |
        towncrier --yes
        make doc
      displayName: 'Run docs checker'
      env:
        AIOHTTP_NO_EXTENSIONS: 1

  - job: 'twine'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
      displayName: 'Install deps'
      env:
        AIOHTTP_NO_EXTENSIONS: 1

    - script: |
        twine check dist/*
      displayName: 'Run twine checker'

  - job: 'contributors'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        LC_ALL=C sort -c CONTRIBUTORS.txt
      displayName: 'Making sure that CONTRIBUTORS.txt remains sorted'
