name: Clear needs-info on comment
on:
  issue_comment:
    types: [created]

jobs:
  clear-needs-info:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Remove needs-info label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs-info
